
# api-key is your Middleware API Key obtained by logging 
# into your Middleware account
api-key: <your api key> 

# target is your unique Middleware account URL
target: https://<your-unique-subdomain>.middleware.io

# Synthetic monitoring using the Middleware agent is disabled by default.
# Set enable-synthetic-monitoring to true if you want this agent to be
# able to perform synthetic tests.
enable-synthetic-monitoring: true

# The duration for the agent to check for configuration changes from the
# backend. We recommend to keep this change to 5 minutes or higher. Keeping 
# this duration to a smaller value will impact resource consumption on the
# host.
config-check-interval: "5m"
