name: Build & Push Docker Image for Host Agent
on:
  push:
    branches:
    #  - 'main'
    #  - 'releases/**'
     - 'master'
    #  - 'dev'

jobs:
  push_to_docker_registry:
    name: Build & Push Docker Image for Host Agent
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Login to Registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USER }}
          password: ${{ secrets.GHCR_TOKEN }} # Consists Github Personal Access Token

      - name: Extract Metadata
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ghcr.io/middleware-labs/agent-host-go

      - name: Build and Push
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      
      - name: Updating otel-config.yaml in install.middleware.io
        run: |
          git clone https://.:${{ secrets.GHCR_TOKEN }}@github.com/middleware-labs/install.middleware.io.git
          cp configyamls/all/otel-config.yaml install.middleware.io/configyamls/all/otel-config.yaml 
          cp configyamls/nodocker/otel-config.yaml install.middleware.io/configyamls/nodocker/otel-config.yaml 
          cd install.middleware.io
          git config --global user.email "keval@middleware.io"
          git config --global user.name "bhogayatakb"
          git add .
          git commit -m "install.middleware.io updated"
          git push origin master
